
local cfg = {}

cfg.groups = {
	["dev"] = {
        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",

		"admin.entityshit",

        "admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.gangAddGroups",
--dono groups
		"group.add.bronze",
		"group.add.silver",
		"group.add.gold",
		"group.add.diamond",
		"group.add.platinum",
--dono groups
		"group.add.vipgarage",
        "group.add.staffmanager",
        "group.add.commdirect",
		"group.add.leadcardev",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

--dono groups
		"group.remove.bronze",
		"group.remove.silver",
		"group.remove.gold",
		"group.remove.diamond",
		"group.remove.platinum",
--dono groups

		"group.remove.vipgarage",
        "group.remove.staffmanager",
        "group.remove.commdirect",
		"group.remove.leadcardev",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"group.add.vipgarage",
        "group.add.founder",
        "group.add.staffmanager",
        "group.add.commdirect",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

		"group.remove.vipgarage",
        "group.remove.founder",
        "group.remove.staffmanager",
        "group.remove.commdirect",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		"admin.noclip",
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
	},
	["founder"] = {
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",

		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",
		"admin.gangAddGroups",

		"group.add.vipgarage",
        "group.add.founder",
        "group.add.staffmanager",
        "group.add.commdirect",
        "group.add.headadmin",
        "group.add.senioradmin",
		"group.add.leadcardev",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",
		"admin.noclip",
		"group.remove.vipgarage",
        "group.remove.founder",
        "group.remove.staffmanager",
        "group.remove.commdirect",
        "group.remove.headadmin",
        "group.remove.senioradmin",
		"group.remove.leadcardev",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",

		--dono groups
		"group.add.bronze",
		"group.add.silver",
		"group.add.gold",
		"group.add.diamond",
		"group.add.platinum",
		--dono groups		
		--dono groups
        "group.remove.bronze",
		"group.remove.silver",
		"group.remove.gold",
		"group.remove.diamond",
		"group.remove.platinum",
		--dono groups

		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",

		"admin.entityshit",

	},
	["staffmanager"] = {
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",
		"admin.gangAddGroups",
		"admin.noclip",
		"admin.whitelisted",
		"admin.tickets",

		"admin.entityshit",



	},
	["generalmanager"] = {

        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",

		"admin.entityshit",

        "admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.gangAddGroups",

		"group.add.vipgarage",
        "group.add.staffmanager",
        "group.add.commdirect",
		"group.add.leadcardev",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

		"group.remove.vipgarage",
        "group.remove.staffmanager",
        "group.remove.commdirect",
		"group.remove.leadcardev",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"group.add.vipgarage",
        "group.add.staffmanager",
        "group.add.commdirect",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

		"group.remove.vipgarage",
        "group.remove.staffmanager",
        "group.remove.commdirect",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		"admin.noclip",
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",

		--dono groups
		"group.add.bronze",
		"group.add.silver",
		"group.add.gold",
		"group.add.diamond",
		"group.add.platinum",
		--dono groups		
		--dono groups
        "group.remove.bronze",
		"group.remove.silver",
		"group.remove.gold",
		"group.remove.diamond",
		"group.remove.platinum",
		--dono groups

	},
	["commdirect"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.getgroups",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.givemoney",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
		
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.licenseAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",
	"admin.gangAddGroups",
	"admin.noclip",
	"admin.noclip",
	"admin.whitelisted",
	"admin.tickets",
	"admin.entityshit",

	},
	["headadmin"] = {
	"admin.menu",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.screenshot",
    "admin.slap",
    "admin.tp2waypoint",
    "admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
			
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.licenseAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",
	"admin.noclip",
	"group.add.vipgarage",
    "group.add",
	
	"admin.whitelisted",
	"admin.tickets",

		--dono groups
		"group.add.bronze",
		"group.add.silver",
		"group.add.gold",
		"group.add.diamond",
		"group.add.platinum",
		--dono groups		
		--dono groups
        "group.remove.bronze",
		"group.remove.silver",
		"group.remove.gold",
		"group.remove.diamond",
		"group.remove.platinum",
		--dono groups


  },
  ["senioradmin"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
		
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",
	"admin.noclip",
	"group.add.vipgarage",
    "group.add",
	
	"admin.whitelisted",
	"admin.tickets",
  },
  ["leadcardev"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.noclip",
	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
	"dev.menu",
	"dev.spawncar",
	"dev.deletecar",
	"dev.fixcar",
	"admin.vehmenu",
  },
  ["administrator"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.noclip",
	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
  },
  ["srmoderator"] = {
    "admin.menu",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.screenshot",
    "admin.tp2waypoint",
    "admin.tp2coords",
    "admin.whitelisted",
    "admin.tickets",
    "admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
    },
  ["moderator"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.screenshot",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
  },
  ["supportteam"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.screenshot",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
  },
  ["trialstaff"] = {
    "admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.kick",
	"admin.nof10kick",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.tp2coords",
	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
  },

--[[STAFF PERMS START ABOVE]]--
  ["user"] = {
    "player.phone",
    "player.calladmin",
	"player.fix_haircut",
	"player.check",
    "police.askid",
    "police.store_weapons",
	"player.skip_coma",
	"player.store_money",
	"player.check",
	"player.loot",
	"player.player_menu",
	"player.userlist",
    "police.seizable",
	"user.paycheck"
  },

  ["BlackOps Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"cop.glock",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"blackops.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Black Ops"] = {
    "blackops.clockon",
	"clockon.menu",
  },

  ["Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"cop.glock",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"commissioner.paycheck",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"com.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Commissioner"] = {
    "commissioner.clockon",
	"clockon.menu",
  },

  ["Deputy Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
	"police.getoutveh",
	"deputycommissioner.paycheck",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
	"police.seize.weapons",
	"cop.glock",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"depcom.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Deputy Commissioner"] = {
    "depcommissioner.clockon",
	"clockon.menu",
  },

  ["Assistant Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"assistantcommissioner.paycheck",
    "police.getoutveh",
	"police.service",
	"cop.glock",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"assistcom.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Assistant Commissioner"] = {
    "asscommissioner.clockon",
	"clockon.menu",
  },

  ["Deputy Assistant Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
	"police.getoutveh",
	"assistantdeputycommissioner.paycheck",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"cop.glock",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"depassist.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Deputy Assistant Commissioner"] = {
    "depasscommissioner.clockon",
	"clockon.menu",
  },

  ["Commander Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"commander.paycheck",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"cop.glock",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"com.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Commander"] = {
    "commander.clockon",
	"clockon.menu",
  },

  ["BlackOPS Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"cop.glock",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"blackops.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["BlackOPS"] = {
    "blackops.clockon",
	"clockonblackops.menu",
  },

  ["Chief Superintendent Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"chiefsuperintendent.paycheck",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
	"police.seize.items",
	"cop.glock",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"chiefsupt.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Chief Superintendent"] = {
    "chiefsupint.clockon",
	"clockon.menu",
  },

  ["Superintendent Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"cop.glock",
	"police.wanted",
	"superintendent.paycheck",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"supt.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Superintendent"] = {
    "superint.clockon",
	"clockon.menu",
  },

  ["Chief Inspector Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
	"police.service",
	"chiefinspector.paycheck",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
	"cop.glock",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"chiefinspector.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Chief Inspector"] = {
    "chiefinsp.clockon",
	"clockon.menu",
  },

  ["Inspector Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"inspector.paycheck",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"cop.glock",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"inspector.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Inspector"] = {
    "inspector.clockon",
	"clockon.menu",
  },

  ["Sergeant Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"sergeant.paycheck",
	"police.easy_unjail",
	"cop.glock",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"sergeant.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Sergeant"] = {
    "sgt.clockon",
	"clockon.menu",
  },

  ["Special Police Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"cop.glock",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
	"police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"spc.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Special Police Constable"] = {
    "specialpc.clockon",
	"clockon.menu",
  },

  ["Senior Police Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"police.wanted",
	"cop.glock",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
	"police.announce",
	"spc.paycheck",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"seniorpc.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Senior Police Constable"] = {
    "srpc.clockon",
	"clockon.menu",
  },

  ["Police Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"cop.glock",
	"response.armor",
	"policeconstable.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Police Constable"] = {
    "pc.clockon",
	"clockon.menu",
  },

  ["PCSO Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
	  onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"cop.glock",
	"pcso.armor",
	"pcso.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["PCSO"] = {
    "pcso.clockon",
	"clockon.menu",
  },

  ["SCO-19"] = {
    "sco.armoury",
  },

  -- [[ NHS Clocked On Groups ]]--

  ["Head Chief Medical Officer Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Assistant Chief Medical Officer Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Deputy Chief Medical Officer Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Captain Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Consultant Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Specialist Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Senior Doctor Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Junior Doctor Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Critical Care Paramedic Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Paramedic Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  ["Trainee Paramedic Clocked"] = {
    "nhs.revive",
	"nhs.heal",
	"nhs.menu",
  },

  --[[ NHS Clock On Groups ]]--
  ["Head Chief Medical Officer"] = {
    "hcmo.clockon",
	"clockon.nhs",
  },

  ["Assistant Chief Medical Officer"] = {
    "acmo.clockon",
	"clockon.nhs",
  },

  ["Deputy Chief Medical Officer"] = {
    "dcmo.clockon",
	"clockon.nhs",
  },

  ["Captain"] = {
    "capt.clockon",
	"clockon.nhs",
  },

  ["Consultant"] = {
    "consultant.clockon",
	"clockon.nhs",
  },

  ["Specialist"] = {
    "specialist.clockon",
	"clockon.nhs",
  },

  ["Senior Doctor"] = {
    "srdoctor.clockon",
	"clockon.nhs",
  },

  ["Junior Doctor"] = {
    "jrdoctor.clockon",
	"clockon.nhs",
  },

  ["Critical Care Paramedic"] = {
    "ccp.clockon",
	"clockon.nhs",
  },

  ["Paramedic"] = {
    "paramedic.clockon",
	"clockon.nhs",
  },

  ["Trainee Paramedic"] = {
    "tparamedic.clockon",
	"clockon.nhs",
  },

 -- [[LEGAL JOBS]]
    ["diamond1"] = {
		"diamond.license"
	},

  --[[ Drug Licenses ]]--
  ["weed"] = {
    "weed.license"
  },
  ["coke"] = {
    "coke.license"
  },
  ["ecstasy"] = {
    "ecstasy.license"
  },
  ["meth"] = {
    "meth.license"
  },
  ["heroin"] = {
    "heroin.license"
  },

  ["AA"] = {
	  "aa.job"
  },

  ["streamer"] = {
	  "streamer.job"
  },


  ["scrap"] = {
	  "scrap.job"
  },

  -- [[WHITELISTED GANGS]]
  ["sicario"] = {
	  "sicario.door",
	  "sicario.armoury",
  },

  ["nazarious"] = {
	"nazarious.door",
	"nazarious.armoury",
},


  --[[ Gunstore Licenses ]]--
  ["blackmarket"] = {
    "blackmarket.license"
  },
  ["rebel"] = {
    "rebel.license"
  },
  ["bronze"] = "Bronze",
  ["silver"] = "Silver",
  ["gold"] = "Gold",
  ["platinum"] = "Platinum",
  ["diamond"] = "Diamond",
  --[[ Donation Ranks ]]
  ["vipgarage"] = {
    "vip.garage"
  },
  ["bronze"] = {
    "vip.garage"
  },
  ["silver"] = {
    "vip.garage"
  },
  ["gold"] = {
    "vip.garage"
  },
  ["platinum"] = {
    "vip.garage"
  },
  ["diamond"] = {
    "vip.garage"
  },





  --[[ User Ranks ]]
  ["pov"] = {},

	--[[ Job Ranks ]]
	["DPD"] = {},
	













	--[[GANGS]]

	["anonymous"] = {
		"anon.perms",
	},
	["lawfirm"] = {
		"lawyer.perms",
	},
}

cfg.users = {
  [1] = {
    "founder",
    "dev",
  },
  [2] = {
	  "founder",
	  "dev"
  }
}

cfg.selectors = {}

return cfg
