AddTextEntry("WEAPON_VANDAL", "Reaver Vandel")
AddTextEntry("WEAPON_RUSTLR300", "LR300 Rust")
AddTextEntry("WEAPON_MONTANA", "MONTANA")
AddTextEntry("WEAPON_NAILGUN", "NAILGUN")
AddTextEntry("WEAPON_HUSHGHOST", "Hush Ghost")
AddTextEntry("WEAPON_LIQUIDCARBINE", "Liquid Carbine")
AddTextEntry("WEAPON_MILITIA", "Militia")
AddTextEntry("WEAPON_HAHA74U", "Laughing Ak-74u")
AddTextEntry("WEAPON_REDTIGER", "Red Tiger M13")
AddTextEntry("WEAPON_P226", "P226 Sig Sauer")
AddTextEntry("WEAPON_SCOUSEGLOCK", "Glock 18 Scouse")
AddTextEntry("WEAPON_NIKEPISTOL", "Nike Pistol")
AddTextEntry("WEAPON_ETHANGLOCK", "Ethan Glock")
AddTextEntry("WEAPON_JOKEREXMMZ", "Joker Pistol")
AddTextEntry("WEAPON_NSR", "NSR-9")
AddTextEntry("WEAPON_AR15", "AR-15")
AddTextEntry("WEAPON_M1911", "M1911")
AddTextEntry("WEAPON_ACR1", "ACR1")
AddTextEntry("WEAPON_SCARL", "SCAR-L")
AddTextEntry("WEAPON_UMP45", "UMP-45")
AddTextEntry("WEAPON_OLYMPIA", "OLYMPIA")
AddTextEntry("WEAPON_G36C", "G-36C")
AddTextEntry("WEAPON_MP5X", "MP5X")
AddTextEntry("WEAPON_GLOCK", "GLOCK")
AddTextEntry("WEAPON_TX15", "TX15")
AddTextEntry("WEAPON_MOSIN", "MOSIN")
AddTextEntry("WEAPON_VESPER", "VESPER")
AddTextEntry("WEAPON_RUSSIANSNIPER", "RUSSIAN SNIPER")
AddTextEntry("WEAPON_STAFFGUN", "DELETE GUN")
AddTextEntry("WEAPON_HUSHG", "HUSH GHOST")
AddTextEntry("WEAPON_M870", "REMINGTON M870")
AddTextEntry("WEAPON_SIGMPX", "SIG MPX")
AddTextEntry("WEAPON_P90HYPERBEAST", "P90 HYPERBEAST")
AddTextEntry("WEAPON_R700", "R700 SNIPER")
AddTextEntry("WEAPON_WALTHERP99", "Walther P-99")
AddTextEntry("WEAPON_M4A1SPURPLE", "M4A1 Purple")
AddTextEntry("WEAPON_ELDERVANDAL", "Elder Vandal")
AddTextEntry("WEAPON_GAMBINO", "Gambino")
AddTextEntry("WEAPON_7IT2", "Glock 17 NeoNoir")
AddTextEntry("WEAPON_BLACKOPSAR", "Black OPS AR")
AddTextEntry("WEAPON_BLACKOPSSMG", "Black OPS SMG")
AddTextEntry("WEAPON_BLACKOPSPISTOL", "Black OPS Pistol")
AddTextEntry("WEAPON_BLACKOPSSNIPER", "Black OPS Sniper")
AddTextEntry("WEAPON_BLACKOPSTAZER", "Black OPS Tazer")
AddTextEntry("WEAPON_MP5SDGALAXY", "Galaxy MP5-SD")
AddTextEntry("WEAPON_UWUDUBZYLILLI", "UWU DUBZY X LILLI")
AddTextEntry("WEAPON_ASM1", "ASM1")
AddTextEntry("WEAPON_GDEAGLE", "Golden Deagle")
AddTextEntry("WEAPON_WOODENBAT", "Wooden Bat")
AddTextEntry("WEAPON_SINGULARITYKNIFE", "Singularity Knife")
AddTextEntry("WEAPON_SHANK", "Shank")
AddTextEntry("WEAPON_KATANASWORD", "Katana Sword")
AddTextEntry("WEAPON_DILDO", "Dildo")
AddTextEntry("WEAPON_BROOM", "Broom")
AddTextEntry("WEAPON_M4SICARIO", "Sicario M4")
AddTextEntry("WEAPON_NAZARIOUS", "Nazarious BAR")
AddTextEntry("WEAPON_HK416A", "HK416A")
AddTextEntry("WEAPON_KILLCONFIRMED", "USP-S Kill Confirmed")

