-- define items, see the Inventory API on github

-- define items, see the Inventory API on github

local cfg = {}
-- see the manual to understand how to create parametric items
-- idname = {name or genfunc, description or genfunc, genfunc choices or nil, weight or genfunc}
-- a good practice is to create your own item pack file instead of adding items here

 cfg.weapons = {
  "WEAPON_BARRETHVC",
  "WEAPON_SPAR17HVC",
  "WEAPON_G36KHVC", 
  "WEAPON_SIGMCXHVC",
  "WEAPON_MP5HVC", 
  "WEAPON_GLOCK17HVC",
  "WEAPON_BATONHVC", 
  "WEAPON_MOSINHVC", 
  "WEAPON_KASHNARHVC",
  "WEAPON_AK74HVC",
  "WEAPON_UMPHVC", 
  "WEAPON_MK1EMRHVC",
  "WEAPON_MXMHVC", 
  "WEAPON_SPAR16HVC",
  "WEAPON_SVDHVC", 
  "WEAPON_AK200HVC", 
  "WEAPON_LR300HVC", 
  "WEAPON_M1911HVC", 
  "WEAPON_UZIHVC",
  "WEAPON_MAKAROVHVC",
  "WEAPON_GUITARHVC",
  "WEAPON_SHANKHVC",
  "WEAPON_TOILETBRUSHHVC",
  "WEAPON_KITCHENHVC",
  "WEAPON_CRUTCHHVC",
  "WEAPON_BUTTERFLYHVC",
  "WEAPON_SPEEDGUNHVC",
  "WEAPON_REMINGTON870HVC",
  "WEAPON_WINCHESTER12HVC",
  "WEAPON_PQ15HVC",
  "WEAPON_BARRET50HVC",
  "WEAPON_MSRHVC", 
  "WEAPON_SV98HVC",
  "WEAPON_M4A1SDECIMATORHVC",
  "WEAPON_M4A1SSAGIRIRHVC",
  "WEAPON_CNDYRIFLEHVC",
  "WEAPON_AUGHVC",
  "WEAPON_GRAUHVC",
  "WEAPON_VANDALHVC", 
  "WEAPON_NV4HVC", 
  "WEAPON_HONEYBADGERHVC",
  "WEAPON_HK418HVC",
  "WEAPON_SCORPBLUEHVC",
  "WEAPON_PERFORATORHVC", 
  "WEAPON_GUNGIRLDEAGLEHVC",
  "WEAPON_SAKURADEAGLEHVC",
  "WEAPON_PRINTSTREAMDEAGLEHVC",
  "WEAPON_KILLCONFIRMEDDEAGLEHVC",
  "WEAPON_TINTHVC",
  "WEAPON_ASIIMOVPISTOLHVC",
  "WEAPON_VOMFEUERHVC",
  "WEAPON_HOWLHVC",
  "WEAPON_HAHAHVC",
  "WEAPON_GDEAGLEHVC",
  "WEAPON_PICKHVC",
  "WEAPON_HOBBYHVC",
  "WEAPON_LIGHTSABERHVC",
  "WEAPON_KATANAHVC",
  "WEAPON_SPHANTOMHVC",
  "WEAPON_ADAGGERHVC",
  "WEAPON_CAPSHIELDHVC",
  "WEAPON_L96HVC",
  "WEAPON_MP7A2HVC",
  "WEAPON_M107HVC",
  "WEAPON_M4A1SNIGHTMAREHVC",
  "WEAPON_PILUMHVC",
  "WEAPON_HAYMAKERHVC",
  "WEAPON_USPSTORQUEHVC",
  "WEAPON_REAVERVANDALHVC",
  "WEAPON_M4A1HVC",
  "WEAPON_SCARHVC",
  "WEAPON_MP5A2HVC",
  "WEAPON_IRONWOLFHVC",
  "WEAPON_LIQUIDCARBINEHVC",
  "WEAPON_M82A2HVC",
  "WEAPON_M82A3HVC",
  "WEAPON_GUNGNIRHVC",
  "WEAPON_BORAHVC",
  "WEAPON_HADDESNIPERHVC",
  "WEAPON_M98BHVC",
  "WEAPON_M200HVC",
  "WEAPON_ORSIST5000HVC",
  "WEAPON_MSR2HVC",
  "WEAPON_STACHVC",
  "WEAPON_RIFLEV2HVC",
  "WEAPON_VALHVC",
  "WEAPON_M4A4HYBRIDHVC",
  "WEAPON_M4A4FIREHVC",
  "WEAPON_NERFBLASTERHVC",
  "WEAPON_MXHVC",
  "WEAPON_M60HVC",
  "WEAPON_USAS12HVC",
  "WEAPON_HKV2HVC",
  "WEAPON_HK416HVC",
  "WEAPON_FNFALHVC",
  "WEAPON_DRAGONAKHVC",
  "WEAPON_MK18HVC", 
  "WEAPON_M16A4HVC",
  "WEAPON_M13HVC",
  "WEAPON_RAINBOWLR300HVC",
  "WEAPON_ICEDRAKEHVC",
  "WEAPON_M203HVC",
  "WEAPON_M4FBXHVC",
  "WEAPON_M4HVC",
  "WEAPON_M4A4NOIRHVC",
  "WEAPON_M4A1SNEONOIRHVC",
  "WEAPON_M4A1SPURPLEHVC",
  "WEAPON_MK18V2HVC",
  "WEAPON_PRIMEVANDALHVC",
  "WEAPON_ORIGINVANDALHVC",
  "WEAPON_REDTIGERHVC",
  "WEAPON_SP1HVC",
  "WEAPON_M4A4RIOTHVC",
  "WEAPON_M4A4RETROHVC",
  "WEAPON_XM4TIGERHVC",
  "WEAPON_AUGV2HVC",
  "WEAPON_DIAMONDMP5HVC",
  "WEAPON_MTARGLOWCHVC",
  "WEAPON_MP5GLOWHVC",
  "WEAPON_MP5A3HVC",
  "WEAPON_MPXCHVC",
  "WEAPON_P90HVC",
  "WEAPON_P90V2HVC",
  "WEAPON_PRIMESPECTREHVC",
  "WEAPON_SCORPEVOEHVC",
  "WEAPON_SINGULARITYSPECTREHVC",
  "WEAPON_T5GLOWHVC",
  "WEAPON_VSSHVC",
  "WEAPON_VESPERHVC",
  "WEAPON_VESPERHYBRIDHVC",
  "WEAPON_ARESSHRIKEHVC",
  "WEAPON_FNMAGHVC",
  "WEAPON_M60V2HVC",
  "WEAPON_MK249HVC",
  "WEAPON_DEADPOOLSHOTGUNHVC",
  "WEAPON_HAYMAKERV2HVC",
  "WEAPON_PUMPSHOTGUNMK2HVC",
  "WEAPON_SPAS12HVC",
  "WEAPON_RPK16HVC",
  "WEAPON_AK47KITTYREVENGEHVC",
  "WEAPON_L118A1HVC",
  "WEAPON_MINIMIM249HVC",
  "WEAPON_SR25HVC",
  "WEAPON_ANIMESWORDHVC",
  "WEAPON_wuxiafanHVC",
  "WEAPON_ANIMEMAC10HVC",
  "WEAPON_DIAMONDSWORDHVC",
  "WEAPON_GLITCHPOPOPERATORHVC",
  "WEAPON_RE6HVC",
  "WEAPON_RE6RNHVC",
  "WEAPON_RE6SNIPERHVC",
  "WEAPON_M4A4NEVAHVC",
  "WEAPON_AK74UV3HVC",
  "WEAPON_SR25HVC",
  "WEAPON_ANIMESWORDHVC",
  "WEAPON_wuxiafanHVC",
  "WEAPON_ANIMEMAC10HVC",
  "WEAPON_DIAMONDSWORDHVC",
  "WEAPON_ODINHVC",
  "WEAPON_BLASTXPHANTOMHVC",
  "WEAPON_M4A4DRAGONKINGHVC",
  "WEAPON_BAL27HVC",
  "WEAPON_PURPLENIKEGRAUHVC",
  "WEAPON_AKCQBHVC",
  "WEAPON_HEADSTONEAUGHVC",
  "WEAPON_FFARHVC",
  "WEAPON_PARAFALSOULREAPERHVC",
  "WEAPON_ORIGINVANDALYELLOWHVC",
  "WEAPON_ACRCQBHVC",
  "WEAPON_AK74UGOKU",
  "WEAPON_M249HVC",
  "WEAPON_LVOAHVC",
  "WEAPON_NERFMOSINHVC",
  "WEAPON_GLITCHPOPPHANTOMHVC",
  "WEAPON_VITYAZ",
  "WEAPON_VTSGLOWHVC",
  "WEAPON_TACGLOCK19",
  "WEAPON_AWPMIKU",
  "WEAPON_HKMP5K",
  "WEAPON_MODEL680",
  "WEAPON_SVDK",
  "WEAPON_G28",
  "WEAPON_FIVESEVENHVC",
  "WEAPON_SIGSAUERP226R",
  "WEAPON_COLTM16A2HVC",
  "WEAPON_MWUZIHVC",
  "WEAPON_FX05HVC",
  "WEAPON_TX15",
  "WEAPON_M14",
  "WEAPON_RPD",
  "WEAPON_FFARAUTOTOONHVC",
  "WEAPON_SIGHVC",
  "WEAPON_GSCYTHE",
  "WEAPON_PK470",
  "WEAPON_IBAK",
  "WEAPON_ODINX",
  "WEAPON_HBRA3",
  "WEAPON_AN94",
  "WEAPON_HKMG4",
  "WEAPON_S75",
  "WEAPON_M77",
  "WEAPON_AR160",
  "WEAPON_M40A3",
  "WEAPON_ELDERVANDAL",
  "WEAPON_RGXVANDAL",
  "WEAPON_REAVEROPERATOR",
  "WEAPON_WARHEAD",
  "WEAPON_WARHEADAR",
  "WEAPON_STAC",
  "WEAPON_PHAN",
  "WEAPON_SOLBLUE",
  "WEAPON_HAWKM4",
  "WEAPON_REAVERVANDALWHITE",
  "WEAPON_M249PLAYMAKER",
  "WEAPON_XM177",
  "WEAPON_MK18CQBR",
  "WEAPON_M16A2",
  "WEAPON_MK18V2",
  "WEAPON_DEAGLE",
  "WEAPON_IMPULSEAK47",
  "WEAPON_SAIGRY",
  "WEAPON_GLOWAUG",
}



cfg.items = {
  -- {Backpacks}
  ["wbody|WEAPON_MOSINHVC"] = {"Mosin", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_KASHNARHVC"] = {"AK47 Kashnar", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AK74HVC"] = {"AK47", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SPAR16HVC"] = {"SPAR-16", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_UMPHVC"] = {"UMP-45", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MK1EMRHVC"] = {"MK1-EMR", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PQ15HVC"] = {"ANPQ-15", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MXMHVC"] = {"MXM", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SVDHVC"] = {"SVD", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_AK200HVC"] = {"AK-200", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_LR300HVC"] = {"LR-300", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HOWLHVC"] = {"M4A4 Howl", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M1911HVC"] = {"M1911", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_UZIHVC"] = {"UZI", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MAKAROVHVC"] = {"Makarov", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_GUITARHVC"] = {"Guitar", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_SHANKHVC"] = {"Shank", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_TOILETBRUSHHVC"] = {"Toilet Brush", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_KITCHENHVC"] = {"Kitchen Knife", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_CRUTCHHVC"] = {"Crutch", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_BUTTERFLYHVC"] = {"Butterfly Knife", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_WINCHESTER12HVC"] = {"Winchester-12", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_BARRET50HVC"] = {"Barret-50 Cal", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_MSRHVC"] = {"MSR", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_SV98HVC"] = {"SV98", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M4A1SDECIMATORHVC"] = {"M4A1 Decimator", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4A1SSAGIRIRHVC"] = {"M4A1 Sagiri", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_CNDYRIFLEHVC"] = {"Candy Rifle", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AUGHVC"] = {"AUG", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_GRAUHVC"] = {"Grau", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_VANDALHVC"] = {"Vandal", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_NV4HVC"] = {"NV4", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HONEYBADGERHVC"] = {"Honey Badger", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HK418HVC"] = {"HK418", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SCORPBLUEHVC"] = {"Scorpion Blue", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HAHAHVC"] = {"Laughing 74-U", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PERFORATORHVC"] = {"Perforator", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_GUNGIRLDEAGLEHVC"] = {"Gun Girl Deagle", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_SAKURADEAGLEHVC"] = {"Sakura Deagle", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_PRINTSTREAMDEAGLEHVC"] = {"Print Stream Deagle", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_KILLCONFIRMEDDEAGLEHVC"] = {"Kill Confirmed Deagle", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_TINTHVC"] = {"White Tint Deagle", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_ASIIMOVPISTOLHVC"] = {"Asiimov Pistol", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_VOMFEUERHVC"] = {"Vom Feuer", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_PPSHHVC"] = {"PPSH", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MISTHVC"] = {"Mist Splitter", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_FINNHVC"] = {"Adventure Time Pistol", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_FNX45HVC"] = {"FNX 45", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_KARAMBITHVC"] = {"Karambit Knife", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_CARB2HVC"] = {"Carbon Rifle Mk2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4A1SSAGIRIHVC"] = {"M4A1 Sagiri", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_GDEAGLEHVC"] = {"Golden Deagle", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PICKHVC"] = {"Diamond Pickaxe", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_HOBBYHVC"] = {"Hobby Horse", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_LIGHTSABERHVC"] = {"Lightsaber", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_KATANAHVC"] = {"Thermal Katana", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_SPHANTOMHVC"] = {"Singularity Phantom", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ADAGGERHVC"] = {"Ancient Dagger", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_CAPSHIELDHVC"] = {"Captain America Shield", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_L96HVC"] = {"No Mercy L96", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_TIGERHVC"] = {"Tiger Blade", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_LEVIATHANHVC"] = {"Leviathan Axe", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_MP7A2HVC"] = {"MP7A2", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_M107HVC"] = {"M107", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M4A1SNIGHTMAREHVC"] = {"M4A1S Nightmare", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PILUMHVC"] = {"Roman Pilum", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_HAYMAKERHVC"] = {"Haymaker", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_USPSTORQUEHVC"] = {"UPS-S Torque", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_REAVERVANDALHVC"] = {"Reaver Vandal", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M4A1HVC"] = {"M4A1", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_SCARHVC"] = {"Scar", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MP5A2HVC"] = {"MP5A2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_IRONWOLFHVC"] = {"M4A1S Iron Wolf", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_LIQUIDCARBINEHVC"] = {"Liquid Carbine", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M82A2HVC"] = {"M82A2", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M82A3HVC"] = {"M82A3", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_GUNGNIRHVC"] = {"Gungnir", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_BORAHVC"] = {"Bora", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_HADDESNIPERHVC"] = {"Hadde Sniper", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M98BHVC"] = {"M98B", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M200HVC"] = {"M200", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_ORSIST5000HVC"] = {"Orsist 5000", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_MSR2HVC"] = {"MSR 2", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_STACHVC"] = {"Stac", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_RIFLEV2HVC"] = {"Rifle V2", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_VALHVC"] = {"AS Val", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M4A4HYBRIDHVC"] = {"M4A4 Hybrid", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M4A4FIREHVC"] = {"M4A4 Fire", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_NERFBLASTERHVC"] = {"Nerf Blaster", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_MXHVC"] = {"MX", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M60HVC"] = {"M60", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_USAS12HVC"] = {"Usas 12", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HKV2HVC"] = {"HKV2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HK416HVC"] = {"HK416", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_FNFALHVC"] = {"FN FAL", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_DRAGONAKHVC"] = {"Dragon AK", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MK18HVC"] = {"MK18", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M16A4HVC"] = {"M16A4", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M13HVC"] = {"M13", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_RAINBOWLR300HVC"] = {"Rainbow LR300", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ICEDRAKEHVC"] = {"Ice Drake", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M203HVC"] = {"M203", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4FBXHVC"] = {"M4FBX", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4HVC"] = {"M4", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4A4NOIRHVC"] = {"M4A4 Noir", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4A1SNEONOIRHVC"] = {"M4A1S Neon Noir", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4A1SPURPLEHVC"] = {"M4A1S Purple", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MK18V2HVC"] = {"MK18V2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PRIMEVANDALHVC"] = {"Prime Vandal", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ORIGINVANDALHVC"] = {"Origin Vandal", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_REDTIGERHVC"] = {"Red Tiger", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SP1HVC"] = {"SP1", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4A4RIOTHVC"] = {"M4A4 Riot", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4A4RETROHVC"] = {"M4A4 Retro", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_XM4TIGERHVC"] = {"XM4 Tiger", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AUGV2HVC"] = {"AUG MK2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_DIAMONDMP5HVC"] = {"Diamond MP5", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MTARGLOWCHVC"] = {"MTAR Glow", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MP5GLOWHVC"] = {"MP5 Glow", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MP5A3HVC"] = {"MP5A3", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MPXCHVC"] = {"MPXC", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_P90HVC"] = {"P90", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_P90V2HVC"] = {"P90 V2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PRIMESPECTREHVC"] = {"Prime Spectre", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SCORPEVOEHVC"] = {"Scorpion Evo", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SINGULARITYSPECTREHVC"] = {"Singularity Spectre", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_T5GLOWHVC"] = {"T5 Glow", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_VSSHVC"] = {"VSS", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_VESPERHVC"] = {"Vesper", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_VESPERHYBRIDHVC"] = {"Vesper Hybrid", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ARESSHRIKEHVC"] = {"Ares Shrike", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_FNMAGHVC"] = {"FN MAG", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M60V2HVC"] = {"M60 V2", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_MK249HVC"] = {"MK249", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_DEADPOOLSHOTGUNHVC"] = {"Deadpool Shotgun", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HAYMAKERV2HVC"] = {"Haymaker V2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PUMPSHOTGUNMK2HVC"] = {"Pump Shotgun Mk2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SPAS12HVC"] = {"SPAS12", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_RPK16HVC"] = {"RPK 16", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AK47KITTYREVENGEHVC"] = {"AK-47 Kitty Revenge", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_L118A1HVC"] = {"L118A1", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MINIMIM249HVC"] = {"Minimi M249", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SR25HVC"] = {"SR-25", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ANIMESWORDHVC"] = {"Anime Sword", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_wuxiafanHVC"] = {"Wuxia Fan", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_ANIMEMAC10HVC"] = {"Anime Mac10", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_DIAMONDSWORDHVC"] = {"Diamond Sword", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_GLITCHPOPOPERATORHVC"] = {"Glitchpop Operator", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_RE6HVC"] = {"RE6", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_RE6RNHVC"] = {"RE6RN", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_RE6SNIPERHVC"] = {"RE6 Sniper", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_M4A4NEVAHVC"] = {"M4A4 Neva", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AK74UV3HVC"] = {"AK74U v3", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SR25HVC"] = {"SR25", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ANIMESWORDHVC"] = {"Anime Sword", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_wuxiafanHVC"] = {"Wuxia Fan", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ANIMEMAC10HVC"] = {"Anime Mac 10", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_DIAMONDSWORDHVC"] = {"Diamond Sword", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ODINHVC"] = {"Glitchpop Odin", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_BLASTXPHANTOMHVC"] = {"Blast X Phantom", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M4A4DRAGONKINGHVC"] = {"M4A4 DragonKing", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_BAL27HVC"] = {"BAL 27", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PURPLENIKEGRAUHVC"] = {"Purple Nike Grau", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AKCQBHVC"] = {"AK CQB", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HEADSTONEAUGHVC"] = {"Headstone AUG", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_FFARHVC"] = {"FFAR", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_PARAFALSOULREAPERHVC"] = {"Parafal Soul Reaper", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ORIGINVANDALYELLOWHVC"] = {"Origin Vandal Yellow", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ACRCQBHVC"] = {"ACR CQB", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AK74UGOKU"] = {"AK74U Goku", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M249HVC"] = {"M249", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_LVOAHVC"] = {"LVOA-C", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_NERFMOSINHVC"] = {"Nerf Mosin", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_VITYAZ"] = {"Vityaz", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_VTSGLOWHVC"] = {"VTS Glow", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_GLITCHPOPPHANTOMHVC"] = {"Glitchpop Phantom", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_TACGLOCK19"] = {"Tactical Glock 19", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_AWPMIKU"] = {"AWP Miku", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_HKMP5K"] = {"HKMP5K", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_MODEL680"] = {"MODEL 680", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_SVDK"] = {"SVDK", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_G28"] = {"G28", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_FIVESEVENHVC"] = {"Five Seven", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_SIGSAUERP226R"] = {"Sig Sauer P226R", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_COLTM16A2HVC"] = {"Colt M16A2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MWUZIHVC"] = {"MW UZI", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_FX05HVC"] = {"FX-05", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_TX15"] = {"TX-15", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M14"] = {"M14", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_RPD"] = {"RPD", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_FFARAUTOTOONHVC"] = {"FFAR Auto Toon", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SIGHVC"] = {"SIG MPX", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_GSCYTHE"] = {"Grims Scythe", "Bomb", nil, 1.00, "weapon"},
  ["wbody|WEAPON_PK470"] = {"PK 470", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_IBAK"] = {"IBAK", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ODINX"] = {"ODIN X", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_HBRA3"] = {"HBRA3", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AN94"] = {"AN94", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HKMG4"] = {"HK MG4", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_S75"] = {"S75", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M77"] = {"M77", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_AR160"] = {"AR160", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M40A3"] = {"M40A3", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_ELDERVANDAL"] = {"Elderflame Vandal", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_RGXVANDAL"] = {"RGX Vandal", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_REAVEROPERATOR"] = {"Reaver Operator", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_WARHEAD"] = {"Warhead Sniper", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_WARHEADAR"] = {"Warhead", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_STAC"] = {"Stac", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_PHAN"] = {"Phantom", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SOLBLUE"] = {"SOL Blue", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_HAWKM4"] = {"HAWK M4", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_REAVERVANDALWHITE"] = {"Reaver Vandal White", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M249PLAYMAKER"] = {"M249 Playmaker", "Bomb", nil, 7.50, "weapon"},
  ["wbody|WEAPON_XM177"] = {"XM177", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MK18CQBR"] = {"MK18 CQBR", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_M16A2"] = {"M16A2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_MK18V2"] = {"MK18 V2", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_DEAGLE"] = {"Desert Eagle", "Bomb", nil, 2.50, "weapon"},
  ["wbody|WEAPON_IMPULSEAK47"] = {"Impulse AK47", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_SAIGRY"] = {"Sai Gry AR15", "Bomb", nil, 5.00, "weapon"},
  ["wbody|WEAPON_GLOWAUG"] = {"Glow Aug", "Bomb", nil, 5.00, "weapon"},

  -- {Weapon Weights}

  -- {Assault-Rifles | 5KG Bodies | 0.01KG Ammo} --
  -- {LMGs | 7.5KG Bodies | 0.01KG Ammo} --okay,
  -- {Melees | 1KG Bodies} --
  -- {Pistols | 2.50KG | 0.01KG Ammo} --
  -- {Shotguns | 5KG Bodies | 0.01KG Ammo} --
  -- {Smgs | 5KG Bodies | 0.01KG Ammo} --
  -- {Sniper-Rifles | 7.50KG | 0.01KG Ammo} --

  -- {{Assault-Rifles | 5KG Bodies | 0.01KG Ammo}  --

  -- {Items | Weight Depends On What The Weapon Is | HVC Items} --

  ["credit"] = {"Stolen Credit Card", "Credit card.", nil, 0.01}, -- no choices
  ["driver"] = {"Driver license Card", "license card.", nil, 0.01}, -- no choices
  ["bank_money"] = {"Money of bank", "$.", nil, 0},
  ["trash"] = {"Trash", "It fucking stinks!", nil, 0},  -- no choices
  ["fake_id"] = {"Fake ID", "It just says Mcluvin.", nil, 0}, -- no choices
  ["police_report"] = {"Police Report", "Take it to the Bank Manager.", nil, 0},  -- no choices
  ["ems_report"] = {"EMS Report", "Take it to the Hospital.", nil, 0}, -- no choices
  ["cargo"] = {"Cargo", "Boxes full of porn.", nil, 0}, -- no choices

  -- {Custom Items} --

  -- {Drugs | 1KGS Unprocessed} -- 
  ["opiumpoppy"] = {"Opium Poppy", "Opium Poppy", nil, 1.00}, 
  ["heroin"] = {"Heroin", "1 Heroin", nil, 5.00},

  ["cocaplant"] = {"Coca Plant", "Coca Plant", nil, 1.00},
  ["cocaine"] = {"Cocaine", "1 Cocaine", nil, 5.00},

  ["crystalmeth"] = {"Crystal Meth", "Crystal Meth", nil, 1.00},
  ["meth"] = {"Meth", "1 Meth", nil, 5.00},

  ["virolabarkresin"] = {"Virola Bark Resin", "Virola Bark Resin", nil, 1.00},
  ["bottlesofdistilledwater"] = {"Bottles of Distilled Water", "Bottles of distilled water", nil, 1.00},
  ["muriaticacid"] = {"Muriatic Acid", "Muriatic Acid", nil, 1.00},
  ["dmt"] = {"DMT", "1 DMT", nil, 5.00},

  ["froglegs"] = {"Frog Legs", "Frog Legs", nil, 1.00},
  ["lysergicacidamid"] = {"Lysergic Acid Amid", "Lysergic Acid Amid", nil, 1.00},
  ["lsd"] = {"LSD", "LSD", nil, 5.00},

  ["sassafrastreeoil"] = {"Sassafras Tree Oil", "Sassafras Tree Oil", nil, 1.00},
  ["mdma"] = {"MDMA", "1 MDMA", nil, 5.00},

  ["weedleaves"] = {"Weed Leaves", "Weed Leaves", nil, 1.00},
  ["weed"] = {"Weed", "1 Weed", nil, 5.00},

  ["unprocessedcoal"] = {"Unprocessed Coal", "Unprocessed Coal", nil, 1.00},
  ["coal"] = {"Coal", "1 Coal", nil, 5.00},

  ["unprocessediron"] = {"Unprocessed Iron", "Unprocessed Iron", nil, 1.00},
  ["iron"] = {"Iron", "1 Iron", nil, 5.00},

  ["unprocessedgold"] = {"Unprocessed Gold", "Unprocessed Gold", nil, 1.00},
  ["gold"] = {"Gold", "1 Gold", nil, 5.00},

  ["unprocessedethereum"] = {"Unprocessed Ethereum", "Unprocessed Ethereum", nil, 1.00},
  ["ethereum"] = {"Ethereum", "1 Ethereum", nil, 5.00},

  ["crudeoil"] = {"Crude Oil", "Crude Oil", nil, 1.00},
  ["oil"] = {"Oil", "1 Oil", nil, 5.00},

  ["uncutdiamonds"] = {"Uncut Diamonds", "Uncut Diamonds", nil, 1.00},
  ["diamonds"] = {"Diamond", "1 Diamond", nil, 5.00},


  ["guccipouch"] = {"Gucci Pouch", "Just A Gucci Pouch", nil, 5.00},
  ["nikeschoolbackpack"] = {"Nike School Backpack", "Just A Nike School Backpack", nil, 5.00}, 
  ["louisvuittonbag"] = {"Louis Vuitton Bag", "Just A Louis Vuitton Bag", nil, 5.00},
  ["rebelpack"] = {"Rebel Backpack", "Just A Rebel Backpack", nil, 5.00},


  --- {REQUIRED FOR BANK HIEST}
  ["drill"] = {"Heist Drill", "Just A Drill", nil, 0.20},
  ["bag"] = {"Heist Bag", "Just A Bag", nil, 0.01},
  ["cutter"] = {"Cutter Blade", "Just A Cutter", nil, 0.20},
  ["c4_bomb"] = {"C4", "Just A C4", nil, 1.00},
  ["thermite_bomb"] = {"Sticky Thermite", "Just A Thermite", nil, 0.05},
  ["laptop"] = {"Laptop", "Just A Laptop", nil, 0.50},
  ["hack_usb"] = {"USB Stick", "Just A USB", nil, 0.10},


  --- {REWARDS FROM HEIST}
  ["goldbar"] = {"Gold Bar", "Just A Bar", nil, 0.50},
  ["diamondbar"] = {"Diamond Bar", "Just A diamonbd bar", nil, 0.50},
  ["coke_pooch"] = {"Cocaine Pouch", "Just A Coke Pouch", nil, 0.50},

  ["vanPogo"] = {"Shiny Pogo Statue", "Just A shiny pogo statue", nil, 1.25},
  ["vanDiamond"] = {"Shiny Diamond", "Just A shiny diamond statue", nil, 1.25},
  ["vanPanther"] = {"Shiny Panther Statue", "Just A shiny panther statue", nil, 1.25},
  ["vanNecklace"] = {"Shiny Necklace", "Just A shiny necklace statue", nil, 1.25},
  ["vanBottle"] = {"Shiny Bottle", "Just A shiny bottle statue", nil, 1.25},
  ["paintingf"] = {"Precious Painting 1", "Just A painting 1", nil, 1.25},
  ["paintingg"] = {"Precious Painting 2", "Just A painting 2", nil, 1.25},

  --- {TOOLS}
  ["Lockpick"] = {"Lockpick", "lockpick ur car", nil, 1.50},
}

-- load more items function
local function load_item_pack(name)
  local items = module("cfg/item/"..name)
  if items then
    for k,v in pairs(items) do
      cfg.items[k] = v
    end
  else
    print("[HVC] item pack ["..name.."] not found")
  end
end

-- PACKS
load_item_pack("required")
load_item_pack("food")
load_item_pack("drugs")

return cfg
